### ISSUE TITLE
dead link?

### ISSUE THREAD

**Issue by shawn0915** [pingcap/tidb-course-201-lab#52]
https://github.com/pingcap/tidb-course-201-lab/blob/master/student-guide/view/en/chapter-ninja-kits/za.md?plain=1#L2
https://github.com/pingcap/tidb-course-201-lab/blob/master/student-guide/view/en2ja/chapter-ninja-kits/za.md?plain=1#L2

链接中 `education-768x497.jpeg` 这张图不存在，是对应新版的这张么 `PE-One-Page-20230512.jpeg`？

**Comment by guangleibao** [comment]
Correct, it should be PE-One-Page-<current>.jpeg.
